# Copyright (c) Facebook, Inc. and its affiliates.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Cookbook Name:: cpe_chrome
# Library:: gen_windows_chrome_known_settings
# rubocop:disable Metrics/LineLength
# @generated
require_relative 'windows_chrome_settingv2'

module CPE
  module ChromeManagement
    module KnownSettings
      GENERATED = {
        'AbusiveExperienceInterventionEnforce' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AbusiveExperienceInterventionEnforce',
          :dword,
          false,
        ),
        'AdsSettingForIntrusiveAdsSites' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AdsSettingForIntrusiveAdsSites',
          :dword,
          false,
        ),
        'AllowCrossOriginAuthPrompt' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AllowCrossOriginAuthPrompt',
          :dword,
          false,
        ),
        'AllowDeletingBrowserHistory' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AllowDeletingBrowserHistory',
          :dword,
          false,
        ),
        'AllowDinosaurEasterEgg' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AllowDinosaurEasterEgg',
          :dword,
          false,
        ),
        'AllowFileSelectionDialogs' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AllowFileSelectionDialogs',
          :dword,
          false,
        ),
        'AllowOutdatedPlugins' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AllowOutdatedPlugins',
          :dword,
          false,
        ),
        'AllowPopupsDuringPageUnload' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AllowPopupsDuringPageUnload',
          :dword,
          false,
        ),
        'AllowSyncXHRInPageDismissal' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AllowSyncXHRInPageDismissal',
          :dword,
          false,
        ),
        'AllowedDomainsForApps' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AllowedDomainsForApps',
          :string,
          false,
        ),
        'AlternateErrorPagesEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'AlternateErrorPagesEnabled',
          :dword,
          false,
        ),
        'AlternativeBrowserPath' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AlternativeBrowserPath',
          :string,
          false,
        ),
        'AlwaysOpenPdfExternally' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AlwaysOpenPdfExternally',
          :dword,
          false,
        ),
        'AmbientAuthenticationInPrivateModesEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AmbientAuthenticationInPrivateModesEnabled',
          :dword,
          false,
        ),
        'ApplicationLocaleValue' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'ApplicationLocaleValue',
          :string,
          false,
        ),
        'AudioCaptureAllowed' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AudioCaptureAllowed',
          :dword,
          false,
        ),
        'AudioSandboxEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AudioSandboxEnabled',
          :dword,
          false,
        ),
        'AuthNegotiateDelegateWhitelist' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AuthNegotiateDelegateWhitelist',
          :string,
          false,
        ),
        'AuthSchemes' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AuthSchemes',
          :string,
          false,
        ),
        'AuthServerWhitelist' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AuthServerWhitelist',
          :string,
          false,
        ),
        'AutofillAddressEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'AutofillAddressEnabled',
          :dword,
          false,
        ),
        'AutofillCreditCardEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'AutofillCreditCardEnabled',
          :dword,
          false,
        ),
        'AutoplayAllowed' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'AutoplayAllowed',
          :dword,
          false,
        ),
        'BackgroundModeEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'BackgroundModeEnabled',
          :dword,
          false,
        ),
        'BlockExternalExtensions' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BlockExternalExtensions',
          :dword,
          false,
        ),
        'BlockThirdPartyCookies' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'BlockThirdPartyCookies',
          :dword,
          false,
        ),
        'BookmarkBarEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'BookmarkBarEnabled',
          :dword,
          false,
        ),
        'BrowserAddPersonEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserAddPersonEnabled',
          :dword,
          false,
        ),
        'BrowserGuestModeEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserGuestModeEnabled',
          :dword,
          false,
        ),
        'BrowserGuestModeEnforced' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserGuestModeEnforced',
          :dword,
          false,
        ),
        'BrowserNetworkTimeQueriesEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserNetworkTimeQueriesEnabled',
          :dword,
          false,
        ),
        'BrowserSignin' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserSignin',
          :dword,
          false,
        ),
        'BrowserSwitcherChromePath' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserSwitcherChromePath',
          :string,
          false,
        ),
        'BrowserSwitcherDelay' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserSwitcherDelay',
          :dword,
          false,
        ),
        'BrowserSwitcherEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserSwitcherEnabled',
          :dword,
          false,
        ),
        'BrowserSwitcherExternalGreylistUrl' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserSwitcherExternalGreylistUrl',
          :string,
          false,
        ),
        'BrowserSwitcherExternalSitelistUrl' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserSwitcherExternalSitelistUrl',
          :string,
          false,
        ),
        'BrowserSwitcherKeepLastChromeTab' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserSwitcherKeepLastChromeTab',
          :dword,
          false,
        ),
        'BrowserSwitcherUseIeSitelist' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BrowserSwitcherUseIeSitelist',
          :dword,
          false,
        ),
        'BuiltInDnsClientEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'BuiltInDnsClientEnabled',
          :dword,
          false,
        ),
        'ChromeCleanupEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ChromeCleanupEnabled',
          :dword,
          false,
        ),
        'ChromeCleanupReportingEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ChromeCleanupReportingEnabled',
          :dword,
          false,
        ),
        'ClickToCallEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ClickToCallEnabled',
          :dword,
          false,
        ),
        'CloudManagementEnrollmentMandatory' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'CloudManagementEnrollmentMandatory',
          :dword,
          false,
        ),
        'CloudManagementEnrollmentToken' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'CloudManagementEnrollmentToken',
          :string,
          false,
        ),
        'CloudPolicyOverridesPlatformPolicy' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'CloudPolicyOverridesPlatformPolicy',
          :dword,
          false,
        ),
        'CloudPrintProxyEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'CloudPrintProxyEnabled',
          :dword,
          false,
        ),
        'CloudPrintSubmitEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'CloudPrintSubmitEnabled',
          :dword,
          false,
        ),
        'CommandLineFlagSecurityWarningsEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'CommandLineFlagSecurityWarningsEnabled',
          :dword,
          false,
        ),
        'ComponentUpdatesEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ComponentUpdatesEnabled',
          :dword,
          false,
        ),
        'CorsLegacyModeEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'CorsLegacyModeEnabled',
          :dword,
          false,
        ),
        'DNSInterceptionChecksEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DNSInterceptionChecksEnabled',
          :dword,
          false,
        ),
        'DefaultBrowserSettingEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultBrowserSettingEnabled',
          :dword,
          false,
        ),
        'DefaultCookiesSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultCookiesSetting',
          :dword,
          false,
        ),
        'DefaultGeolocationSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultGeolocationSetting',
          :dword,
          false,
        ),
        'DefaultImagesSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultImagesSetting',
          :dword,
          false,
        ),
        'DefaultInsecureContentSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultInsecureContentSetting',
          :dword,
          false,
        ),
        'DefaultJavaScriptSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultJavaScriptSetting',
          :dword,
          false,
        ),
        'DefaultNotificationsSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultNotificationsSetting',
          :dword,
          false,
        ),
        'DefaultPluginsSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultPluginsSetting',
          :dword,
          false,
        ),
        'DefaultPopupsSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultPopupsSetting',
          :dword,
          false,
        ),
        'DefaultPrinterSelection' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultPrinterSelection',
          :string,
          false,
        ),
        'DefaultSearchProviderEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderEnabled',
          :dword,
          false,
        ),
        'DefaultSearchProviderIconURL' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderIconURL',
          :string,
          false,
        ),
        'DefaultSearchProviderImageURL' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderImageURL',
          :string,
          false,
        ),
        'DefaultSearchProviderImageURLPostParams' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderImageURLPostParams',
          :string,
          false,
        ),
        'DefaultSearchProviderKeyword' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderKeyword',
          :string,
          false,
        ),
        'DefaultSearchProviderName' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderName',
          :string,
          false,
        ),
        'DefaultSearchProviderNewTabURL' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderNewTabURL',
          :string,
          false,
        ),
        'DefaultSearchProviderSearchURL' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderSearchURL',
          :string,
          false,
        ),
        'DefaultSearchProviderSearchURLPostParams' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderSearchURLPostParams',
          :string,
          false,
        ),
        'DefaultSearchProviderSuggestURL' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderSuggestURL',
          :string,
          false,
        ),
        'DefaultSearchProviderSuggestURLPostParams' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultSearchProviderSuggestURLPostParams',
          :string,
          false,
        ),
        'DefaultWebBluetoothGuardSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultWebBluetoothGuardSetting',
          :dword,
          false,
        ),
        'DefaultWebUsbGuardSetting' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DefaultWebUsbGuardSetting',
          :dword,
          false,
        ),
        'DeveloperToolsAvailability' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DeveloperToolsAvailability',
          :dword,
          false,
        ),
        'Disable3DAPIs' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'Disable3DAPIs',
          :dword,
          false,
        ),
        'DisableAuthNegotiateCnameLookup' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DisableAuthNegotiateCnameLookup',
          :dword,
          false,
        ),
        'DisablePrintPreview' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DisablePrintPreview',
          :dword,
          false,
        ),
        'DisableSafeBrowsingProceedAnyway' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DisableSafeBrowsingProceedAnyway',
          :dword,
          false,
        ),
        'DisableScreenshots' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DisableScreenshots',
          :dword,
          false,
        ),
        'DiskCacheDir' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DiskCacheDir',
          :string,
          false,
        ),
        'DiskCacheSize' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'DiskCacheSize',
          :dword,
          false,
        ),
        'DownloadDirectory' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'DownloadDirectory',
          :string,
          false,
        ),
        'DownloadRestrictions' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'DownloadRestrictions',
          :dword,
          false,
        ),
        'EditBookmarksEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'EditBookmarksEnabled',
          :dword,
          false,
        ),
        'EnableAuthNegotiatePort' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'EnableAuthNegotiatePort',
          :dword,
          false,
        ),
        'EnableMediaRouter' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'EnableMediaRouter',
          :dword,
          false,
        ),
        'EnableOnlineRevocationChecks' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'EnableOnlineRevocationChecks',
          :dword,
          false,
        ),
        'EnterpriseHardwarePlatformAPIEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'EnterpriseHardwarePlatformAPIEnabled',
          :dword,
          false,
        ),
        'ExtensionSettings' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ExtensionSettings',
          :string,
          false,
        ),
        'ExternalProtocolDialogShowAlwaysOpenCheckbox' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ExternalProtocolDialogShowAlwaysOpenCheckbox',
          :dword,
          false,
        ),
        'ForceEphemeralProfiles' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ForceEphemeralProfiles',
          :dword,
          false,
        ),
        'ForceGoogleSafeSearch' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ForceGoogleSafeSearch',
          :dword,
          false,
        ),
        'ForceNetworkInProcess' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ForceNetworkInProcess',
          :dword,
          false,
        ),
        'ForceYouTubeRestrict' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ForceYouTubeRestrict',
          :dword,
          false,
        ),
        'FullscreenAllowed' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'FullscreenAllowed',
          :dword,
          false,
        ),
        'GloballyScopeHTTPAuthCacheEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'GloballyScopeHTTPAuthCacheEnabled',
          :dword,
          false,
        ),
        'HardwareAccelerationModeEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'HardwareAccelerationModeEnabled',
          :dword,
          false,
        ),
        'HideWebStoreIcon' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'HideWebStoreIcon',
          :dword,
          false,
        ),
        'HomepageIsNewTabPage' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'HomepageIsNewTabPage',
          :dword,
          false,
        ),
        'HomepageLocation' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'HomepageLocation',
          :string,
          false,
        ),
        'ImportAutofillFormData' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'ImportAutofillFormData',
          :dword,
          false,
        ),
        'ImportBookmarks' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'ImportBookmarks',
          :dword,
          false,
        ),
        'ImportHistory' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'ImportHistory',
          :dword,
          false,
        ),
        'ImportHomepage' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ImportHomepage',
          :dword,
          false,
        ),
        'ImportSavedPasswords' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'ImportSavedPasswords',
          :dword,
          false,
        ),
        'ImportSearchEngine' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'ImportSearchEngine',
          :dword,
          false,
        ),
        'IncognitoModeAvailability' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'IncognitoModeAvailability',
          :dword,
          false,
        ),
        'IsolateOrigins' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'IsolateOrigins',
          :string,
          false,
        ),
        'LegacySameSiteCookieBehaviorEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'LegacySameSiteCookieBehaviorEnabled',
          :dword,
          false,
        ),
        'ManagedBookmarks' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ManagedBookmarks',
          :string,
          false,
        ),
        'MaxConnectionsPerProxy' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'MaxConnectionsPerProxy',
          :dword,
          false,
        ),
        'MaxInvalidationFetchDelay' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'MaxInvalidationFetchDelay',
          :dword,
          false,
        ),
        'MediaRouterCastAllowAllIPs' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'MediaRouterCastAllowAllIPs',
          :dword,
          false,
        ),
        'MetricsReportingEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'MetricsReportingEnabled',
          :dword,
          false,
        ),
        'NTPCustomBackgroundEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'NTPCustomBackgroundEnabled',
          :dword,
          false,
        ),
        'NativeMessagingUserLevelHosts' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'NativeMessagingUserLevelHosts',
          :dword,
          false,
        ),
        'NetworkPredictionOptions' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'NetworkPredictionOptions',
          :dword,
          false,
        ),
        'NewTabPageLocation' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'NewTabPageLocation',
          :string,
          false,
        ),
        'PasswordLeakDetectionEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'PasswordLeakDetectionEnabled',
          :dword,
          false,
        ),
        'PasswordManagerEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'PasswordManagerEnabled',
          :dword,
          false,
        ),
        'PasswordProtectionChangePasswordURL' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PasswordProtectionChangePasswordURL',
          :string,
          false,
        ),
        'PasswordProtectionWarningTrigger' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PasswordProtectionWarningTrigger',
          :dword,
          false,
        ),
        'PaymentMethodQueryEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PaymentMethodQueryEnabled',
          :dword,
          false,
        ),
        'PolicyAtomicGroupsEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PolicyAtomicGroupsEnabled',
          :dword,
          false,
        ),
        'PolicyRefreshRate' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PolicyRefreshRate',
          :dword,
          false,
        ),
        'PrintHeaderFooter' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'PrintHeaderFooter',
          :dword,
          false,
        ),
        'PrintPreviewUseSystemDefaultPrinter' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'PrintPreviewUseSystemDefaultPrinter',
          :dword,
          false,
        ),
        'PrintingAllowedBackgroundGraphicsModes' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PrintingAllowedBackgroundGraphicsModes',
          :string,
          false,
        ),
        'PrintingBackgroundGraphicsDefault' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PrintingBackgroundGraphicsDefault',
          :string,
          false,
        ),
        'PrintingEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PrintingEnabled',
          :dword,
          false,
        ),
        'PromotionalTabsEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PromotionalTabsEnabled',
          :dword,
          false,
        ),
        'PromptForDownloadLocation' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'PromptForDownloadLocation',
          :dword,
          false,
        ),
        'ProxyBypassList' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ProxyBypassList',
          :string,
          false,
        ),
        'ProxyMode' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ProxyMode',
          :string,
          false,
        ),
        'ProxyPacUrl' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ProxyPacUrl',
          :string,
          false,
        ),
        'ProxyServer' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ProxyServer',
          :string,
          false,
        ),
        'ProxySettings' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ProxySettings',
          :string,
          false,
        ),
        'QuicAllowed' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'QuicAllowed',
          :dword,
          false,
        ),
        'RelaunchNotification' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RelaunchNotification',
          :dword,
          false,
        ),
        'RelaunchNotificationPeriod' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RelaunchNotificationPeriod',
          :dword,
          false,
        ),
        'RemoteAccessHostAllowClientPairing' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostAllowClientPairing',
          :dword,
          false,
        ),
        'RemoteAccessHostAllowFileTransfer' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostAllowFileTransfer',
          :dword,
          false,
        ),
        'RemoteAccessHostAllowGnubbyAuth' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostAllowGnubbyAuth',
          :dword,
          false,
        ),
        'RemoteAccessHostAllowRelayedConnection' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostAllowRelayedConnection',
          :dword,
          false,
        ),
        'RemoteAccessHostAllowUiAccessForRemoteAssistance' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostAllowUiAccessForRemoteAssistance',
          :dword,
          false,
        ),
        'RemoteAccessHostFirewallTraversal' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostFirewallTraversal',
          :dword,
          false,
        ),
        'RemoteAccessHostRequireCurtain' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostRequireCurtain',
          :dword,
          false,
        ),
        'RemoteAccessHostTokenUrl' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostTokenUrl',
          :string,
          false,
        ),
        'RemoteAccessHostTokenValidationCertificateIssuer' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostTokenValidationCertificateIssuer',
          :string,
          false,
        ),
        'RemoteAccessHostTokenValidationUrl' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostTokenValidationUrl',
          :string,
          false,
        ),
        'RemoteAccessHostUdpPortRange' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RemoteAccessHostUdpPortRange',
          :string,
          false,
        ),
        'RendererCodeIntegrityEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RendererCodeIntegrityEnabled',
          :dword,
          false,
        ),
        'RequireOnlineRevocationChecksForLocalAnchors' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RequireOnlineRevocationChecksForLocalAnchors',
          :dword,
          false,
        ),
        'RestoreOnStartup' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'RestoreOnStartup',
          :dword,
          false,
        ),
        'RestrictSigninToPattern' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RestrictSigninToPattern',
          :string,
          false,
        ),
        'RoamingProfileLocation' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RoamingProfileLocation',
          :string,
          false,
        ),
        'RoamingProfileSupportEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RoamingProfileSupportEnabled',
          :dword,
          false,
        ),
        'RunAllFlashInAllowMode' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'RunAllFlashInAllowMode',
          :dword,
          false,
        ),
        'SSLErrorOverrideAllowed' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SSLErrorOverrideAllowed',
          :dword,
          false,
        ),
        'SSLVersionMin' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SSLVersionMin',
          :string,
          false,
        ),
        'SafeBrowsingEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'SafeBrowsingEnabled',
          :dword,
          false,
        ),
        'SafeBrowsingExtendedReportingEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SafeBrowsingExtendedReportingEnabled',
          :dword,
          false,
        ),
        'SafeBrowsingForTrustedSourcesEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'SafeBrowsingForTrustedSourcesEnabled',
          :dword,
          false,
        ),
        'SafeSitesFilterBehavior' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SafeSitesFilterBehavior',
          :dword,
          false,
        ),
        'SavingBrowserHistoryDisabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SavingBrowserHistoryDisabled',
          :dword,
          false,
        ),
        'SearchSuggestEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'SearchSuggestEnabled',
          :dword,
          false,
        ),
        'SharedClipboardEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SharedClipboardEnabled',
          :dword,
          false,
        ),
        'ShowAppsShortcutInBookmarkBar' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ShowAppsShortcutInBookmarkBar',
          :dword,
          false,
        ),
        'ShowCastIconInToolbar' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ShowCastIconInToolbar',
          :dword,
          false,
        ),
        'ShowHomeButton' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'ShowHomeButton',
          :dword,
          false,
        ),
        'SignedHTTPExchangeEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SignedHTTPExchangeEnabled',
          :dword,
          false,
        ),
        'SitePerProcess' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SitePerProcess',
          :dword,
          false,
        ),
        'SpellCheckServiceEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'SpellCheckServiceEnabled',
          :dword,
          false,
        ),
        'SpellcheckEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SpellcheckEnabled',
          :dword,
          false,
        ),
        'StricterMixedContentTreatmentEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'StricterMixedContentTreatmentEnabled',
          :dword,
          false,
        ),
        'SuppressUnsupportedOSWarning' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SuppressUnsupportedOSWarning',
          :dword,
          false,
        ),
        'SyncDisabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'SyncDisabled',
          :dword,
          false,
        ),
        'TLS13HardeningForLocalAnchorsEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'TLS13HardeningForLocalAnchorsEnabled',
          :dword,
          false,
        ),
        'TabFreezingEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'TabFreezingEnabled',
          :dword,
          false,
        ),
        'TaskManagerEndProcessEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'TaskManagerEndProcessEnabled',
          :dword,
          false,
        ),
        'ThirdPartyBlockingEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'ThirdPartyBlockingEnabled',
          :dword,
          false,
        ),
        'TranslateEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'TranslateEnabled',
          :dword,
          false,
        ),
        'UrlKeyedAnonymizedDataCollectionEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'UrlKeyedAnonymizedDataCollectionEnabled',
          :dword,
          false,
        ),
        'UserDataDir' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'UserDataDir',
          :string,
          false,
        ),
        'UserFeedbackAllowed' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'UserFeedbackAllowed',
          :dword,
          false,
        ),
        'VideoCaptureAllowed' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'VideoCaptureAllowed',
          :dword,
          false,
        ),
        'WPADQuickCheckEnabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'WPADQuickCheckEnabled',
          :dword,
          false,
        ),
        'WebAppInstallForceList' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'WebAppInstallForceList',
          :string,
          false,
        ),
        'WebComponentsV0Enabled' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'WebComponentsV0Enabled',
          :dword,
          false,
        ),
        'WebRtcEventLogCollectionAllowed' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'WebRtcEventLogCollectionAllowed',
          :dword,
          false,
        ),
        'WebRtcUdpPortRange' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'WebRtcUdpPortRange',
          :string,
          false,
        ),
        'WebUsbAllowDevicesForUrls' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'WebUsbAllowDevicesForUrls',
          :string,
          false,
        ),
        'AlternativeBrowserParameters' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\AlternativeBrowserParameters',
          nil,
          :string,
          true,
        ),
        'AudioCaptureAllowedUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\AudioCaptureAllowedUrls',
          nil,
          :string,
          true,
        ),
        'AutoSelectCertificateForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\AutoSelectCertificateForUrls',
          nil,
          :string,
          true,
        ),
        'AutoplayWhitelist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\AutoplayWhitelist',
          nil,
          :string,
          true,
        ),
        'BrowserSwitcherChromeParameters' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\BrowserSwitcherChromeParameters',
          nil,
          :string,
          true,
        ),
        'BrowserSwitcherUrlGreylist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\BrowserSwitcherUrlGreylist',
          nil,
          :string,
          true,
        ),
        'BrowserSwitcherUrlList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\BrowserSwitcherUrlList',
          nil,
          :string,
          true,
        ),
        'CertificateTransparencyEnforcementDisabledForCas' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\CertificateTransparencyEnforcementDisabledForCas',
          nil,
          :string,
          true,
        ),
        'CertificateTransparencyEnforcementDisabledForLegacyCas' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\CertificateTransparencyEnforcementDisabledForLegacyCas',
          nil,
          :string,
          true,
        ),
        'CertificateTransparencyEnforcementDisabledForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\CertificateTransparencyEnforcementDisabledForUrls',
          nil,
          :string,
          true,
        ),
        'CookiesAllowedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\CookiesAllowedForUrls',
          nil,
          :string,
          true,
        ),
        'CookiesBlockedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\CookiesBlockedForUrls',
          nil,
          :string,
          true,
        ),
        'CookiesSessionOnlyForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\CookiesSessionOnlyForUrls',
          nil,
          :string,
          true,
        ),
        'CorsMitigationList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\CorsMitigationList',
          nil,
          :string,
          true,
        ),
        'DefaultSearchProviderAlternateURLs' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\DefaultSearchProviderAlternateURLs',
          nil,
          :string,
          true,
        ),
        'DefaultSearchProviderEncodings' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\DefaultSearchProviderEncodings',
          nil,
          :string,
          true,
        ),
        'EnableDeprecatedWebPlatformFeatures' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\EnableDeprecatedWebPlatformFeatures',
          nil,
          :string,
          true,
        ),
        'ExtensionAllowedTypes' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\ExtensionAllowedTypes',
          nil,
          :string,
          true,
        ),
        'ExtensionInstallBlacklist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\ExtensionInstallBlacklist',
          nil,
          :string,
          true,
        ),
        'ExtensionInstallForcelist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\ExtensionInstallForcelist',
          nil,
          :string,
          true,
        ),
        'ExtensionInstallSources' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\ExtensionInstallSources',
          nil,
          :string,
          true,
        ),
        'ExtensionInstallWhitelist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\ExtensionInstallWhitelist',
          nil,
          :string,
          true,
        ),
        'HSTSPolicyBypassList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\HSTSPolicyBypassList',
          nil,
          :string,
          true,
        ),
        'ImagesAllowedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\ImagesAllowedForUrls',
          nil,
          :string,
          true,
        ),
        'ImagesBlockedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\ImagesBlockedForUrls',
          nil,
          :string,
          true,
        ),
        'InsecureContentAllowedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\InsecureContentAllowedForUrls',
          nil,
          :string,
          true,
        ),
        'InsecureContentBlockedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\InsecureContentBlockedForUrls',
          nil,
          :string,
          true,
        ),
        'JavaScriptAllowedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\JavaScriptAllowedForUrls',
          nil,
          :string,
          true,
        ),
        'JavaScriptBlockedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\JavaScriptBlockedForUrls',
          nil,
          :string,
          true,
        ),
        'LegacySameSiteCookieBehaviorEnabledForDomainList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\LegacySameSiteCookieBehaviorEnabledForDomainList',
          nil,
          :string,
          true,
        ),
        'NativeMessagingBlacklist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\NativeMessagingBlacklist',
          nil,
          :string,
          true,
        ),
        'NativeMessagingWhitelist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\NativeMessagingWhitelist',
          nil,
          :string,
          true,
        ),
        'NotificationsAllowedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\NotificationsAllowedForUrls',
          nil,
          :string,
          true,
        ),
        'NotificationsBlockedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\NotificationsBlockedForUrls',
          nil,
          :string,
          true,
        ),
        'OverrideSecurityRestrictionsOnInsecureOrigin' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\OverrideSecurityRestrictionsOnInsecureOrigin',
          nil,
          :string,
          true,
        ),
        'PasswordProtectionLoginURLs' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\PasswordProtectionLoginURLs',
          nil,
          :string,
          true,
        ),
        'PluginsAllowedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\PluginsAllowedForUrls',
          nil,
          :string,
          true,
        ),
        'PluginsBlockedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\PluginsBlockedForUrls',
          nil,
          :string,
          true,
        ),
        'PolicyDictionaryMultipleSourceMergeList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\PolicyDictionaryMultipleSourceMergeList',
          nil,
          :string,
          true,
        ),
        'PolicyListMultipleSourceMergeList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\PolicyListMultipleSourceMergeList',
          nil,
          :string,
          true,
        ),
        'PopupsAllowedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\PopupsAllowedForUrls',
          nil,
          :string,
          true,
        ),
        'PopupsBlockedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\PopupsBlockedForUrls',
          nil,
          :string,
          true,
        ),
        'PrinterTypeDenyList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\PrinterTypeDenyList',
          nil,
          :string,
          true,
        ),
        'RemoteAccessHostClientDomainList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\RemoteAccessHostClientDomainList',
          nil,
          :string,
          true,
        ),
        'RemoteAccessHostDomainList' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\RemoteAccessHostDomainList',
          nil,
          :string,
          true,
        ),
        'RestoreOnStartupURLs' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended\RestoreOnStartupURLs',
          nil,
          :string,
          true,
        ),
        'SafeBrowsingWhitelistDomains' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\SafeBrowsingWhitelistDomains',
          nil,
          :string,
          true,
        ),
        'SecurityKeyPermitAttestation' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\SecurityKeyPermitAttestation',
          nil,
          :string,
          true,
        ),
        'SpellcheckLanguage' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\SpellcheckLanguage',
          nil,
          :string,
          true,
        ),
        'SpellcheckLanguageBlacklist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\SpellcheckLanguageBlacklist',
          nil,
          :string,
          true,
        ),
        'SyncTypesListDisabled' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\SyncTypesListDisabled',
          nil,
          :string,
          true,
        ),
        'URLBlacklist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\URLBlacklist',
          nil,
          :string,
          true,
        ),
        'URLWhitelist' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\URLWhitelist',
          nil,
          :string,
          true,
        ),
        'VideoCaptureAllowedUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\VideoCaptureAllowedUrls',
          nil,
          :string,
          true,
        ),
        'WebRtcLocalIpsAllowedUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\WebRtcLocalIpsAllowedUrls',
          nil,
          :string,
          true,
        ),
        'WebUsbAskForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\WebUsbAskForUrls',
          nil,
          :string,
          true,
        ),
        'WebUsbBlockedForUrls' => WindowsChromeIterableSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\WebUsbBlockedForUrls',
          nil,
          :string,
          true,
        ),
        'DefaultDownloadDirectory' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'DefaultDownloadDirectory',
          :string,
          false,
        ),
        'RegisteredProtocolHandlers' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome\Recommended',
          'RegisteredProtocolHandlers',
          :string,
          false,
        ),
        'TotalMemoryLimitMb' => WindowsChromeFlatSetting.new(
          'HKEY_LOCAL_MACHINE\Software\Policies\Google\Chrome',
          'TotalMemoryLimitMb',
          :dword,
          false,
        ),
      }.freeze
    end
  end
end
# rubocop:enable Metrics/LineLength
