#!/bin/bash

# Skip manual check
if [ "$1" = 'manualcheck' ]; then
	echo 'Manual check: skipping'
	exit 0
fi

DIR=$(dirname $0)

mkdir -p "$DIR/cache"

admin_users=''

# Loopt through local users, skip users that start with _ and root
for user in $(dscl . -list /Users | grep -v "^_\|^root$") ; do
	ismember=$(dsmemberutil checkmembership -U $user -G admin)
	case $ismember in
		*'user is a member of the group'*) admin_users+=( $user );;
	esac
done

echo ${admin_users[@]} > "$DIR/cache/localadmins.txt"