#!/usr/bin/python
# encoding: utf-8
'''Postflight script'''

import sys
#Added /usr/local/munki to search path
sys.path.append('/usr/local/munki/')
from munkilib import munkicommon
from munkilib import reportcommon
from munkilib import FoundationPlist
import hashlib
import sys
import os

def main():
    '''Main'''
    # get runtype
    if (len(sys.argv) > 1):
        runtype = sys.argv[1]
    else:
        runtype = 'custom'

    # Try to get the munki verbosity level
    verbosity = os.environ.get('MUNKI_VERBOSITY_LEVEL')
    if (verbosity):
        reportcommon.set_verbosity(int(verbosity))
    else:
        reportcommon.set_verbosity(3)

    scriptdir = os.path.realpath(os.path.dirname(sys.argv[0]))

    # Try to run postflight.d
    postflightscriptdir = os.path.join(scriptdir, "postflight.d")
    reportcommon.rundir(postflightscriptdir, runtype, False)

    # Get serial
    hardware_info = munkicommon.get_hardware_info()
    serial = hardware_info.get('serial_number', 'NO_SERIAL')

    items = {} # item list
    report_info = {}
    report_info['console_user'] = "%s" % munkicommon.getconsoleuser()
    report_info['runtype'] = runtype
    report_info['runstate'] = 'done'
    report_info['uptime'] = reportcommon.get_uptime()
    report_info_plist = FoundationPlist.writePlistToString(report_info)
    items = {'reportdata':{'hash':hashlib.md5(report_info_plist).hexdigest(), \
        'data':report_info_plist}}

    # Read config file /Library/Preferences/Munkireport.plist
    config_items = reportcommon.pref('ReportItems') or {}

    for key, val in config_items.items():
        reportcommon.display_detail("Requesting %s" % key)
        items[key] = {'path':val}

    reportcommon.process(serial, items)

    exit(0)

if __name__ == '__main__':
    main()
